 
export enum ErrorCodes {
    USER_ALREADY_EXISTS_ERROR = 'USER_ALREADY_EXISTS_ERROR',
    AUTH_EMAIL_NOT_VERIFIED_ERROR = 'AUTH_EMAIL_NOT_VERIFIED_ERROR',
    AUTH_INCORRECT_PASSWORD_ERROR = 'AUTH_INCORRECT_PASSWORD_ERROR',
    USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export enum SonnerType {
    ERROR = 'error',
    SUCCESS = 'success'
}

export enum ErrorCodesNames {
    USER_NOT_FOUND = 'User not found',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}