 
export enum ErrorCodes {
    USER_ALREADY_EXISTS_ERROR = 'USER_ALREADY_EXISTS_ERROR',
    AUTH_EMAIL_NOT_VERIFIED_ERROR = 'AUTH_EMAIL_NOT_VERIFIED_ERROR',
    AUTH_INCORRECT_PASSWORD_ERROR = 'AUTH_INCORRECT_PASSWORD_ERROR',
    USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  }